# Generated by Django 6.0 on 2025-12-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transacao_options_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='limite_mensal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quanto você pretende gastar por mês?', max_digits=10),
        ),
    ]
